# Generated by Django 5.1.4 on 2025-01-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField(max_length=1000)),
                ('preparation_time', models.PositiveIntegerField(blank=True, help_text='preparation time in minutes eg. 30 or 90', null=True)),
                ('cooking_time', models.PositiveIntegerField(blank=True, help_text='cooking time in minutes', null=True)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_category', to='recipe.category')),
            ],
        ),
    ]
