# Generated by Django 5.1.4 on 2025-01-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_category_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Ingredient_name',
            new_name='ingredient_name',
        ),
    ]
